"""Add display_name to Materials

Revision ID: 4a42e4bf9cac
Revises: fc0998c317b9
Create Date: 2026-04-19 09:48:56.911425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a42e4bf9cac'
down_revision: Union[str, Sequence[str], None] = 'fc0998c317b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=True))

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "UPDATE materials SET display_name = "
            "CASE "
            "WHEN name_brand IS NOT NULL and name_brand != '' THEN name_brand "
            "ELSE base_type "
            "END"
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
