"""Initial schema

Revision ID: 5efef945d131
Revises: 
Create Date: 2026-04-16 10:32:28.351558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efef945d131'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('frequency_passes', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_logs_id'), 'entry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_entry_logs_material_name'), 'entry_logs', ['material_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_logs_material_name'), table_name='entry_logs')
    op.drop_index(op.f('ix_entry_logs_id'), table_name='entry_logs')
    op.drop_table('entry_logs')
    # ### end Alembic commands ###
