"""Add tab power column

Revision ID: 7fdb7f99f0c9
Revises: 12a41bd5d81c
Create Date: 2026-04-18 11:48:04.506857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdb7f99f0c9'
down_revision: Union[str, Sequence[str], None] = '12a41bd5d81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_logs', sa.Column('tab_power', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_logs', 'tab_power')
    # ### end Alembic commands ###
