"""Add materials table

Revision ID: fc0998c317b9
Revises: 7fdb7f99f0c9
Create Date: 2026-04-19 09:27:48.378943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0998c317b9'
down_revision: Union[str, Sequence[str], None] = '7fdb7f99f0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_type', sa.String(), nullable=False),
    sa.Column('name_brand', sa.String(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_id'), ['id'], unique=False)

    with op.batch_alter_table('entry_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('holding_tabs', sa.Text(), nullable=True))

    bind = op.get_bind()
    bind.execute(sa.text("INSERT INTO materials (base_type, name_brand) VALUES ('Other', 'Legacy Data')"))
    bind.execute(sa.text("UPDATE entry_logs SET material_id = 1"))
    bind.execute(sa.text("UPDATE entry_logs SET notes = 'Legacy Material: ' || material_name || COALESCE('\n' || notes, '')"))
    bind.execute(sa.text("UPDATE entry_logs SET holding_tabs = tab_power || '%' WHERE tab_power IS NOT NULL"))

    with op.batch_alter_table('entry_logs', schema=None) as batch_op:
        batch_op.alter_column('material_id', nullable=False)
        batch_op.drop_index('ix_entry_logs_material_name')
        batch_op.create_foreign_key('fk_entry_logs_materials', 'materials', ['material_id'], ['id'])
        batch_op.drop_column('tab_power')
        batch_op.drop_column('material_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('tab_power', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_entry_logs_material_name'), ['material_name'], unique=False)
        batch_op.drop_column('holding_tabs')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('material_id')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_id'))

    op.drop_table('materials')
    # ### end Alembic commands ###
